### ISSUE TITLE
supported for go 1.11 1.12 1.13?

### ISSUE THREAD

**Issue by yangeagle** [petermattis/goid#10]
RT

**Comment by petermattis** [comment]
@yangeagle I’m pretty sure go1.12, go1.12, and go1.13 all work. Do you have any evidence they don’t?

**Comment by yangeagle** [comment]
@petermattis 
I didn't find exact instructions in the documentation, so I asked this question.

OK. perfect. 
Thank you so much.

**Comment by petermattis** [comment]
@yangeagle Yep, the documentation for this package is sparse and not updated on every go release.
