### ISSUE TITLE
Add Support of fast-path execution for s390x

### ISSUE THREAD

**Issue by srinivas-pokala** [petermattis/goid#43]
Significant slowdown of CockroachDb on s390x due to slow path execution. Need to add support of fast path for s390x, similar to x86_64,arm64 platforms.

**Comment by petermattis** [comment]
@srinivas-pokala Are you going to submit a PR to address this? FYI, there is no need to create an issue before submitting a PR. The PR itself can and should describe the problem it is addressing.

**Comment by srinivas-pokala** [comment]
> @srinivas-pokala Are you going to submit a PR to address this? FYI, there is no need to create an issue before submitting a PR. The PR itself can and should describe the problem it is addressing.
Yes, I am raising the PR to address this. Thank's for theis, next instance onwards I will not  create an issue.
