### ISSUE TITLE
gccgo unsupported

### ISSUE THREAD

**Issue by tamird** [petermattis/goid#6]
See https://github.com/golang/sys/commit/e11762ca30adc5b39fdbfd8c4250dabeb8e456d3

**Comment by petermattis** [comment]
Do we need to support gccgo? Is there something specific in the referenced commit that I should be noticing?

**Comment by tamird** [comment]
Not sure if we need or want to support gccgo; I just checked the state of it today and discovered this as a new issue (new since the last time I tried gccgo).

The referenced commit is just there to show how gccgo support was implemented elsewhere.
