### ISSUE TITLE
Is there any plan to support Go 1.10?

### ISSUE THREAD

**Issue by liudanking** [petermattis/goid#9]
RT

**Comment by petermattis** [comment]
Go 1.10 is supported. Why do you think it isn't?

**Comment by liudanking** [comment]
i did not find a file with 1.10 tag

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by petermattis** [comment]
Go1.10 defines build tags for all prior go versions. The build tag in https://github.com/petermattis/goid/blob/master/runtime_go1.9.go causes that file to be built for go1.10.
